name: Run the translation script after every 4 hours

# Schedule the workflow to run every 4 hours
on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
        # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

        # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
        # Install required dependencies
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

        # Run Python script
      - name: Run Python script
        run: python main.py

      # Commit changes
      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update generated files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}